Repository arsentieva/campy-frontend, pull requests merged in 2020-09, with the labels that each got.

#1 Mapwork
  src/AppWithContext.js
  src/components/GoogleMaps/ComplexGrid.js
  src/components/GoogleMaps/LocationItems.js
  src/components/GoogleMaps/Map.js
  src/components/protectedRoutes/ProfilePicUpload.js
Labels: enhancement

#2 Aaron/landing page
  src/components/About.js
  src/components/Footer.js
  src/components/Home.js
  src/components/NavBar.js
  src/components/UserNavBar.js
Labels: enhancement

#3 Mapwork
  .vscode/launch.json
  src/components/GoogleMaps/LocationItems.js
  src/components/GoogleMaps/Map.js
  src/components/auth/Logout.js
Labels: bug

#5 Aaron/location details
  src/components/Calendar.js
  src/components/LocationDetail.js
Labels: enhancement

#8 Aaron/location details
  .env.example
  package-lock.json
  package.json
  public/index.html
  src/Firebase/firebaseConfig.js
  src/components/ImageUpload.js
  src/components/LocationDetail.js
Labels: documentation

#11 Mapwork
  src/AppWithContext.js
  src/Firebase/firebaseConfig.js
  src/components/Calendar.js
  src/components/UserNavBar.js
  src/components/auth/Login.js
  src/components/auth/SignUp.js
Labels: bug

#12 Aaron/images
  package-lock.json
  package.json
  src/components/LocationDetail.js
  src/components/LocationImages.js
Labels: bug, enhancement

#14 Aaron/readme
  README.md
  public/images/Campy-Home.JPG
  public/images/lightLogo2.png
  public/images/logo.png
  public/images/screenshot.png
  src/components/LocationDetail.js
  src/components/LocationImages.js
Labels: documentation

#13 add image to the infowindow of the map marker
  src/components/GoogleMaps/InfoWindowCard.js
  src/components/GoogleMaps/Map.js
Labels: enhancement

#17 Complete image carousel…
  package-lock.json
  package.json
  src/components/LocationDetail.js
  src/components/LocationImages.js
Labels: enhancement

#19 Mapwork
  src/AppWithContext.js
  src/components/GoogleMaps/Explore.js
  src/components/GoogleMaps/LocationItems.js
  src/components/protectedRoutes/MyLocations.js
Labels: enhancement

#20 Update background color to #2a475c for location-details page
  src/components/LocationDetail.js
  src/components/protectedRoutes/AddLocation.js
Labels: enhancement, help wanted

#21 change the style of push to location detail page buttons
  src/components/GoogleMaps/InfoWindowCard.js
  src/components/GoogleMaps/LocationItems.js
  src/components/GoogleMaps/Map.js
Labels: enhancement

#22 Add meta tags to index.html
  public/images/explore-example.JPG
  public/index.html
Labels: enhancement
